#!/bin/bash

set -eu

INCLUDE_DIRS=(grammars ../../ableC/grammars ../*/grammars)
INCLUDES=${INCLUDE_DIRS[@]/#/-I ../}

mkdir -p jars
mkdir -p build
cd build

echo "Building Silver + ableC with vanilla Silver ..."
silver -I ../grammars -I ../../../ableC/grammars edu:umn:cs:melt:exts:silver:ableC:composed:with_ableC
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_ableC.jar ../jars/

echo "Building Silver + ableC + all extensions with Silver + ableC ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_ableC.jar $INCLUDES edu:umn:cs:melt:exts:silver:ableC:composed:with_all
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/

echo "Building Silver + ableC + all extensions with Silver + ableC + all extensions ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar $INCLUDES edu:umn:cs:melt:exts:silver:ableC:composed:with_all
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/
