#!/bin/bash

set -eu

INCLUDE_DIRS=(../../ableC/grammars ../*/grammars)
INCLUDES=${INCLUDE_DIRS[@]/#/-I ../}

export SVJVM_FLAGS="-Xmx3000M -Xss10M"

mkdir -p jars
mkdir -p build
cd build

echo "Building Silver + ableC with vanilla Silver ..."
silver -I ../grammars -I ../../../ableC/grammars $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_ableC
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_ableC.jar ../jars/

echo "Building Silver + ableC + all extensions with Silver + ableC ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_ableC.jar $INCLUDES $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_all
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/

echo "Building Silver + ableC + all extensions with Silver + ableC + all extensions ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar $INCLUDES --clean $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_all
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/
