#!/bin/bash

set -eu

ABLEC_BASE=$(cd ${ABLEC_BASE:-../../ableC} && pwd)
EXTS_BASE=$(cd ${EXTS_BASE:-..} && pwd)
SILVER_ABLEC_BASE=$(pwd)

INCLUDE_DIRS=($ABLEC_BASE/grammars $EXTS_BASE/*/grammars $SILVER_ABLEC_BASE/grammars)
INCLUDES=${INCLUDE_DIRS[@]/#/-I }

export SVJVM_FLAGS="-Xmx10G -Xss15M"

mkdir -p jars
mkdir -p build
cd build

echo "Building Silver + ableC with vanilla Silver ..."
silver -I ../grammars -I $ABLEC_BASE/grammars $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_ableC
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_ableC.jar ../jars/

echo "Building Silver + ableC + base extensions with Silver + ableC ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_ableC.jar $INCLUDES $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_base
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_base.jar ../jars/

echo "Building Silver + ableC + all extensions with Silver + ableC + base extensions ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_base.jar $INCLUDES $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_all
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/

echo "Building Silver + ableC + all extensions with Silver + ableC + all extensions ..."
silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar $INCLUDES --one-jar --clean $@ edu:umn:cs:melt:exts:silver:ableC:composed:with_all
mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/
