#!/bin/bash

# find by default never follows symlinks, so this should be relatively safe:
find . -name "*~" -delete
find . -name "build.xml" -delete
find . -name "*.copperdump.html" -delete
find . -name "*.jar" -delete

rm -rf build/ jars/

