#!/bin/bash

ABLEC_BASE=$(cd ${ABLEC_BASE:-../../ableC} && pwd)

export SVJVM_FLAGS="-Xmx8G -Xss15M"

export GRAMMAR_PATH=$ABLEC_BASE/ableC.jar:silver-ableC.jar:grammars

silver --dont-translate $@ edu:umn:cs:melt:exts:silver:ableC:mda_test
