#!/bin/bash

set -eu

ABLEC_BASE=$(cd ${ABLEC_BASE:-../../ableC} && pwd)
EXTS_BASE=$(cd ${EXTS_BASE:-..} && pwd)
SILVER_ABLEC_BASE=$(pwd)

INCLUDE_DIRS=($ABLEC_BASE/grammars $EXTS_BASE/*/grammars $SILVER_ABLEC_BASE/grammars)
INCLUDES=${INCLUDE_DIRS[@]/#/-I }

SV_BUILD_TARGET=${SV_BUILD_TARGET:-"edu:umn:cs:melt:exts:silver:ableC:composed:with_all"}

export SVJVM_FLAGS="-Xmx5000M -Xss15M"

mkdir -p build
cd build

silver-custom ../jars/edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar $INCLUDES $@ ${SV_BUILD_TARGET}

if [ -f edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ]; then
    mv edu.umn.cs.melt.exts.silver.ableC.composed.with_all.jar ../jars/
fi
